/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "secondary-container": "#aad6ff",
        "on-tertiary-fixed-variant": "#930010",
        "on-primary-container": "#c4d2ff",
        "on-primary": "#ffffff",
        "surface-container": "#eceef0",
        "primary": "#003d9b",
        "surface-dim": "#d8dadc",
        "on-surface": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "surface-tint": "#0c56d0",
        "secondary-fixed-dim": "#9fcbf4",
        "inverse-surface": "#2d3133",
        "tertiary-fixed": "#ffdad6",
        "tertiary": "#8c000e",
        "on-surface-variant": "#434654",
        "on-tertiary-fixed": "#410003",
        "surface-container-highest": "#e0e3e5",
        "background": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#ffc5bf",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#346286",
        "secondary-fixed": "#cce5ff",
        "error": "#ba1a1a",
        "outline": "#737685",
        "outline-variant": "#c3c6d6",
        "tertiary-fixed-dim": "#ffb3ac",
        "surface": "#f7f9fb",
        "on-primary-fixed": "#001848",
        "on-secondary-fixed-variant": "#184a6d",
        "primary-container": "#0052cc",
        "on-primary-fixed-variant": "#0040a2",
        "inverse-primary": "#b2c5ff",
        "primary-fixed-dim": "#b2c5ff",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#b4151d",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#001d31",
        "surface-bright": "#f7f9fb",
        "error-container": "#ffdad6",
        "primary-fixed": "#dae2ff",
        "on-secondary-container": "#2f5e81",
        "surface-variant": "#e0e3e5"
      },
      borderRadius: {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      fontFamily: {
          "headline": ["Manrope", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
